//! Acceptance test for AC9 (MAY) — generated by `autobuilder scaffold`.
//!
//! Project: session-trace-receipt (cli)
//! AC description: A `--trace-filter <type,type,...>` flag restricts captured event types (e.g. --trace-filter=connect,execve) to reduce log size for long iterations.
//! Test predicate: tests/acceptance_ac9.rs — invoke with filter, assert only requested event types in log
//!
//! READ-ONLY after scaffold. To change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold.

#[test]
fn acceptance_ac9() {
    // TODO(edit-agent): implement the test body that verifies the
    // AC description above. Until implemented, this test fails so the
    // iterate-and-prove loop sees a real signal.
    panic!("AC AC9 not yet implemented — see file header");
}
