//! Acceptance test for AC7 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: session-trace-receipt (cli)
//! AC description: Receipt includes tracer.log_sha256 so the raw NDJSON is tamper-evident; recomputing the sha256 of the log on disk must match the receipt.
//! Test predicate: tests/acceptance_ac7.rs — write trusted log, emit receipt, mutate log, assert digest mismatch detected
//!
//! READ-ONLY after scaffold. To change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold.

#[test]
fn acceptance_ac7() {
    // TODO(edit-agent): implement the test body that verifies the
    // AC description above. Until implemented, this test fails so the
    // iterate-and-prove loop sees a real signal.
    panic!("AC AC7 not yet implemented — see file header");
}
