//! Acceptance test for AC8 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: session-trace-receipt (cli)
//! AC description: `--trace` adds <5% wall-clock overhead to the loop on a cargo-test-heavy iteration.
//! Test predicate: benchmark script: 5 traced + 5 untraced iterations against the autobuilder repo, compare median wall-clock
//!
//! READ-ONLY after scaffold. To change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold.

#[test]
fn acceptance_ac8() {
    // TODO(edit-agent): implement the test body that verifies the
    // AC description above. Until implemented, this test fails so the
    // iterate-and-prove loop sees a real signal.
    panic!("AC AC8 not yet implemented — see file header");
}
