//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: session-trace-receipt (cli)
//! AC description: The receipt validates against autobuilder.session_trace_receipt.v1 schema and is digest-bound (sha256 envelope matching other receipts).
//! Test predicate: tests/acceptance_ac3.rs — round-trip parse + digest verify
//!
//! READ-ONLY after scaffold. To change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold.

#[test]
fn acceptance_ac3() {
    // TODO(edit-agent): implement the test body that verifies the
    // AC description above. Until implemented, this test fails so the
    // iterate-and-prove loop sees a real signal.
    panic!("AC AC3 not yet implemented — see file header");
}
