//! Acceptance test for AC4 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: session-trace-receipt (cli)
//! AC description: constraints_evaluated block is populated from intent_card.hard_constraints — only declared constraints appear, each with claimed, an observed counterpart, and a violated bool.
//! Test predicate: tests/acceptance_ac4.rs — intent-card with deny_network:true produces a deny_network entry; intent-card without it does not
//!
//! READ-ONLY after scaffold. To change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold.

#[test]
fn acceptance_ac4() {
    // TODO(edit-agent): implement the test body that verifies the
    // AC description above. Until implemented, this test fails so the
    // iterate-and-prove loop sees a real signal.
    panic!("AC AC4 not yet implemented — see file header");
}
