//! Acceptance test for AC2 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: session-trace-receipt (cli)
//! AC description: When ctrace is unavailable (missing binary, sudo denied, bpftrace missing), `--trace` emits a session-trace.json receipt with verdict=skipped and a skip_reason field; does NOT abort the iteration.
//! Test predicate: tests/acceptance_ac2.rs — mock the ctrace binary path to /bin/false; assert verdict=skipped
//!
//! READ-ONLY after scaffold. To change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold.

#[test]
fn acceptance_ac2() {
    // TODO(edit-agent): implement the test body that verifies the
    // AC description above. Until implemented, this test fails so the
    // iterate-and-prove loop sees a real signal.
    panic!("AC AC2 not yet implemented — see file header");
}
