//! Acceptance test for AC5 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: session-trace-receipt (cli)
//! AC description: When deny_network:true is claimed and the trace contains >=1 connect event, verdict=block.
//! Test predicate: tests/acceptance_ac5.rs — synthesized NDJSON with a connect line, expect block verdict
//!
//! READ-ONLY after scaffold. To change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold.

#[test]
fn acceptance_ac5() {
    // TODO(edit-agent): implement the test body that verifies the
    // AC description above. Until implemented, this test fails so the
    // iterate-and-prove loop sees a real signal.
    panic!("AC AC5 not yet implemented — see file header");
}
