//! Acceptance test for AC6 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: session-trace-receipt (cli)
//! AC description: `autobuilder gate` walks 8 receipts (was 7); existing 7 receipts continue to pass on the autobuilder repo without modification.
//! Test predicate: scripts/run-metrics.sh — smoke against the autobuilder repo, expect receipts=8 pass=8 verdict=pass
//!
//! READ-ONLY after scaffold. To change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold.

#[test]
fn acceptance_ac6() {
    // TODO(edit-agent): implement the test body that verifies the
    // AC description above. Until implemented, this test fails so the
    // iterate-and-prove loop sees a real signal.
    panic!("AC AC6 not yet implemented — see file header");
}
