//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: session-trace-receipt (cli)
//! AC description: `autobuilder loop --trace` shells out to `ctrace start --root <pid>` before the metric-harness spawn and `ctrace stop` after, capturing NDJSON to target/autobuilder/session-trace.ndjson.
//! Test predicate: tests/acceptance_ac1.rs — smoke a traced iteration, assert log file exists and is non-empty
//!
//! READ-ONLY after scaffold. To change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold.

#[test]
fn acceptance_ac1() {
    // TODO(edit-agent): implement the test body that verifies the
    // AC description above. Until implemented, this test fails so the
    // iterate-and-prove loop sees a real signal.
    panic!("AC AC1 not yet implemented — see file header");
}
